const ANGULAR_STEPS_PER_REVOLUTION = (200 * 8 * 32);
const LINEAR_STEPS_PER_SWEEP = 48693;
const LINEAR_CENTER_OFFSET_STEPS = 270;
const LINEAR_MAX_OFFSET_STEPS = 40000;
const LINEAR_RANGE_STEPS = (LINEAR_MAX_OFFSET_STEPS - LINEAR_CENTER_OFFSET_STEPS);

module.exports = {
  ANGULAR_STEPS_PER_REVOLUTION,
  LINEAR_STEPS_PER_SWEEP,
  LINEAR_CENTER_OFFSET_STEPS,
  LINEAR_MAX_OFFSET_STEPS,
  LINEAR_RANGE_STEPS
};