const LARGE_GEAR_TEETH = 128;
const SMALL_GEAR_TEETH = 16;
const MICROSTEP_RATIO = 32;
const ANGULAR_STEPS = 200;
const LINEAR_STEPS_PER_SWEEP = 48693;
const LINEAR_CENTER_OFFSET_STEPS = 270;
const LINEAR_MAX_OFFSET_STEPS = 40000;

const GEAR_RATIO = LARGE_GEAR_TEETH / SMALL_GEAR_TEETH;
const ANGULAR_STEPS_PER_REVOLUTION = (ANGULAR_STEPS * GEAR_RATIO * MICROSTEP_RATIO);
const LINEAR_RANGE_STEPS = (LINEAR_MAX_OFFSET_STEPS - LINEAR_CENTER_OFFSET_STEPS);

module.exports = {
  ANGULAR_STEPS_PER_REVOLUTION,
  LINEAR_STEPS_PER_SWEEP,
  LINEAR_CENTER_OFFSET_STEPS,
  LINEAR_MAX_OFFSET_STEPS,
  LINEAR_RANGE_STEPS
};