const LARGE_GEAR_TEETH = 180;
const SMALL_GEAR_TEETH = 20;
const MICROSTEP_RATIO = 16;
const ANGULAR_STEPS = 200;
const LINEAR_CENTER_OFFSET_STEPS = 135;
const LINEAR_MAX_OFFSET_STEPS = 20000;

const GEAR_RATIO = LARGE_GEAR_TEETH / SMALL_GEAR_TEETH;
const ANGULAR_STEPS_PER_REVOLUTION = (ANGULAR_STEPS * GEAR_RATIO * MICROSTEP_RATIO);
const LINEAR_RANGE_STEPS = (LINEAR_MAX_OFFSET_STEPS - LINEAR_CENTER_OFFSET_STEPS);

module.exports = {
  ANGULAR_STEPS_PER_REVOLUTION,
  LINEAR_CENTER_OFFSET_STEPS,
  LINEAR_MAX_OFFSET_STEPS,
  LINEAR_RANGE_STEPS
};
