#ifndef TABLE_CONSTANTS_H
#define TABLE_CONSTANTS_H

#define ANGULAR_STEPS_PER_REVOLUTION (200 * 8 * 32)
#define LINEAR_STEPS_PER_SWEEP 48693
#define LINEAR_CENTER_OFFSET_STEPS 270
#define LINEAR_MAX_OFFSET_STEPS 40000
#define LINEAR_RANGE_STEPS (LINEAR_MAX_OFFSET_STEPS - LINEAR_CENTER_OFFSET_STEPS)

#endif
